baseurl = "/"
title = "Mara's Twitter Feeds"
author = "Mara Averick"
languagecode = "en-us"
theme = "hugo-black-and-light-theme"
paginate = 10

[permalinks]
  post = "/post/:year/:month/:day/"

[params]
  sitename = "Mara's #rstats Twitter Feeds"

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
[[menu.main]]
    name = "RSS"
    url  = "/index.xml"
    weight = 4

[blackfriday]
  hrefTargetBlank = true
